// File generated by registering the PlantLabWeb app in Firebase project.
// Re-generate with: flutterfire configure (if firebase-tools is installed)

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUCfGYbXqOKidaEdwUtTPvyeD7H6AWMJg',
    appId: '1:115544415132:web:d7014ee003a95bdd064659',
    messagingSenderId: '115544415132',
    projectId: 'plant-lab-simulation-4e1c5',
    authDomain: 'plant-lab-simulation-4e1c5.firebaseapp.com',
    storageBucket: 'plant-lab-simulation-4e1c5.firebasestorage.app',
  );

  // Android / iOS / macOS — not used for the web build.
  // Fill in if you add native targets.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUCfGYbXqOKidaEdwUtTPvyeD7H6AWMJg',
    appId: '1:115544415132:android:placeholder',
    messagingSenderId: '115544415132',
    projectId: 'plant-lab-simulation-4e1c5',
    storageBucket: 'plant-lab-simulation-4e1c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUCfGYbXqOKidaEdwUtTPvyeD7H6AWMJg',
    appId: '1:115544415132:ios:placeholder',
    messagingSenderId: '115544415132',
    projectId: 'plant-lab-simulation-4e1c5',
    storageBucket: 'plant-lab-simulation-4e1c5.firebasestorage.app',
    iosBundleId: 'com.example.plantLabSimulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUCfGYbXqOKidaEdwUtTPvyeD7H6AWMJg',
    appId: '1:115544415132:macos:placeholder',
    messagingSenderId: '115544415132',
    projectId: 'plant-lab-simulation-4e1c5',
    storageBucket: 'plant-lab-simulation-4e1c5.firebasestorage.app',
    iosBundleId: 'com.example.plantLabSimulator',
  );
}
